<?php
/*
 *
 * THIS FILE IS FOR QUICK POPULATION OF THE DATABASE ONLY
 * IT IS NOT RELEVANT TO MY ASSIGNMENT IN ANY OTHER ASPECT
 * 
 * To populate the db, navigate to the page Populate.php
 * It takes about 2-3 seconds after which it will reload Homepage.php.
 * 
 */

include('Functions.php');
include('custom_functions/Database.php');

/* 
 * This users array was generated by ChatGPT 3.5 as a means of coming up with a large amount of fake data.
 * Hopefully this doesn't cause any problems due to this not actually being an assignment requirement
 * 
 * There are 10 users, each with 2 topics, and 10 posts.
 */
$users = array(
    array(
        'username' => 'HappyCat',
        'first_name' => 'Alice',
        'last_name' => 'Smith',
        'short_signature' => 'Always seeking adventure!',
        'topics' => array(
            "Sci-Fi Books",
            "Gaming Communities"
        ),
        'posts' => array(
            "Hey everyone, just joined the forum! Excited to be here.",
            "Does anyone have any recommendations for good sci-fi books?",
            "Just finished watching the latest episode of my favorite TV show, mind-blowing!",
            "Any gamers here? Looking for people to play online with.",
            "Happy Friday, everyone! What are your weekend plans?",
            "Hi all, I'm new here. What's the topic of discussion today?",
            "I need advice on choosing a new laptop. Any suggestions?",
            "Can't believe the weather lately, it's been so unpredictable.",
            "Has anyone tried that new restaurant downtown? Is it any good?",
            "Thinking of starting a new hobby, any ideas?"
        )
    ),
    array(
        'username' => 'SunnyDog',
        'first_name' => 'Bob',
        'last_name' => 'Johnson',
        'short_signature' => 'Sunshine enthusiast!',
        'topics' => array(
            "Productivity Hacks",
            "Mindfulness and Meditation"
        ),
        'posts' => array(
            "Hello fellow forum members, hope you're all doing well.",
            "Just got back from vacation, feeling refreshed!",
            "Looking for recommendations for a good movie to watch tonight.",
            "Does anyone have tips for improving productivity?",
            "What's everyone's favorite way to relax after a long day?",
            "Hi everyone, I'm new here. What's the vibe like on this forum?",
            "I'm having trouble staying motivated with my workout routine. Any advice?",
            "Excited for the upcoming holiday season!",
            "Just discovered a new podcast, highly recommend it.",
            "Does anyone here practice meditation? I'm thinking of giving it a try."
        )
    ),
    array(
        'username' => 'CheerfulPanda',
        'first_name' => 'Carol',
        'last_name' => 'Brown',
        'short_signature' => 'Happiness is contagious!',
        'topics' => array(
            "Writing Tips",
            "Healthy Living"
        ),
        'posts' => array(
            "Hey guys, just checking in. What's happening?",
            "Looking for suggestions for healthy breakfast recipes.",
            "Can't believe how fast this year is flying by!",
            "Does anyone have tips for overcoming writer's block?",
            "What's your favorite thing about this forum?",
            "Greetings everyone, hope you're having a great day!",
            "Just finished reading a fantastic book, highly recommend it.",
            "Does anyone have advice for dealing with stress?",
            "Excited for the weekend, any fun plans?",
            "What's one thing you're grateful for today?"
        )
    ),
    array(
        'username' => 'BreezyTiger',
        'first_name' => 'David',
        'last_name' => 'Williams',
        'short_signature' => 'Embracing life one breeze at a time!',
        'topics' => array(
            "Documentaries",
            "Pet Care"
        ),
        'posts' => array(
            "Hey there, new to the forum. What's the hot topic right now?",
            "Looking for recommendations for good podcasts to listen to.",
            "Feeling inspired today, ready to tackle my goals!",
            "Any pet owners here? Share pics of your furry friends!",
            "Just watched an amazing documentary, really eye-opening.",
            "Hi everyone, hope you're all having a good day!",
            "Can't believe it's already May, time is flying by.",
            "Just tried a new recipe and it turned out delicious!",
            "Need advice on organizing my workspace, it's a mess.",
            "What's one thing you're looking forward to this week?"
        )
    ),
    array(
        'username' => 'LuckyRabbit',
        'first_name' => 'Emma',
        'last_name' => 'Jones',
        'short_signature' => 'Living the lucky life!',
        'topics' => array(
            "Book Recommendations",
            "Travel Experiences"
        ),
        'posts' => array(
            "Hey guys, what's up? Anything exciting happening?",
            "Looking for suggestions for a good workout playlist.",
            "Just finished a great book, now I need something new to read.",
            "Does anyone have tips for improving sleep quality?",
            "What's your favorite thing to do on a lazy Sunday?",
            "Hello everyone, hope you're all doing well.",
            "Just started a new job, feeling a bit nervous but excited too.",
            "Can't wait for the new season of my favorite TV show to start!",
            "Any travelers here? Share your favorite destinations.",
            "What's one piece of advice you would give to your younger self?"
        )
    ),
    array(
        'username' => 'BraveDolphin',
        'first_name' => 'Frank',
        'last_name' => 'Taylor',
        'short_signature' => 'Brave and fearless!',
        'topics' => array(
            "Entrepreneurship",
            "Artistic Pursuits"
        ),
        'posts' => array(
            "Hey everyone, what's the best way to learn a new language?",
            "Just finished a marathon! Feeling accomplished.",
            "Looking for recommendations for a good comedy movie.",
            "I'm considering starting my own business, any tips?",
            "Does anyone else love watching documentaries?",
            "Hi, I'm new here. What's the most popular topic on this forum?",
            "Need advice on dealing with difficult coworkers.",
            "Thinking of adopting a pet, any suggestions?",
            "Just joined a book club, excited to discuss literature!",
            "Happy weekend, everyone! Any exciting plans?"
        )
    ),
    array(
        'username' => 'CleverEagle',
        'first_name' => 'Grace',
        'last_name' => 'Anderson',
        'short_signature' => 'Clever as an eagle!',
        'topics' => array(
            "Interior Design",
            "Literature"
        ),
        'posts' => array(
            "Looking for suggestions for a good restaurant for a date night.",
            "Feeling a bit overwhelmed lately. Any tips for managing stress?",
            "Just finished redecorating my living room, love how it turned out!",
            "Does anyone here enjoy hiking? Share your favorite trails!",
            "Hi all, looking for advice on budgeting and saving money.",
            "What's your favorite thing about spring?",
            "Just discovered a new hobby, knitting! Any fellow knitters here?",
            "Hey guys, any recommendations for a good fantasy book series?",
            "Just got back from a road trip, had a blast!",
            "Thinking of taking up painting as a hobby. Any tips for beginners?"
        )
    ),
    array(
        'username' => 'GentleFox',
        'first_name' => 'Harry',
        'last_name' => 'Martinez',
        'short_signature' => 'Gently roaming through life!',
        'topics' => array(
            "Podcasts",
            "Remote Work"
        ),
        'posts' => array(
            "Looking for suggestions for a good podcast to listen to during workouts.",
            "Hi everyone, hope you're all having a great day!",
            "Can't believe it's already June, where did the time go?",
            "Just completed a DIY project, feeling proud!",
            "Does anyone have tips for staying motivated while working from home?",
            "What's your favorite way to unwind after a busy day?",
            "Hi, I'm new here. What's the most interesting discussion you've had on this forum?",
            "Looking for recommendations for a good thriller novel.",
            "Feeling inspired today, ready to tackle my goals!",
            "Just adopted a rescue dog, meet my new furry friend!"
        )
    ),
    array(
        'username' => 'KindKangaroo',
        'first_name' => 'Ivy',
        'last_name' => 'Rodriguez',
        'short_signature' => 'Kindness is my motto!',
        'topics' => array(
            "Gardening",
            "Documentaries"
        ),
        'posts' => array(
            "Anyone here into gardening? Share your tips and tricks!",
            "Hey everyone, hope you're having a fantastic weekend!",
            "Just finished watching a thought-provoking documentary.",
            "Need advice on improving my photography skills.",
            "Thinking of starting a blog, any tips for beginners?",
            "Looking for recommendations for a good documentary series.",
            "Hi all, what's your favorite way to spend a lazy Sunday?",
            "Just finished writing a short story, feeling accomplished!",
            "Feeling inspired by all the amazing discussions on this forum!",
            "Hey everyone, any recommendations for a good sci-fi movie?"
        )
    ),
    array(
        'username' => 'JollyLion',
        'first_name' => 'Jack',
        'last_name' => 'Brown',
        'short_signature' => 'Roaring with joy!',
        'topics' => array(
            "Career Advice",
            "Fitness"
        ),
        'posts' => array(
            "Just started a new job, feeling excited and a bit nervous.",
            "Looking for advice on improving my public speaking skills.",
            "What's the most interesting place you've traveled to?",
            "Hi, I'm new here. What's the best piece of advice you've received?",
            "Looking for recommendations for a good action movie?",
            "Just got back from a camping trip, had an amazing time!",
            "Looking for advice on meal prepping for the week ahead.",
            "What's the best way to stay organized and productive?",
            "Hi everyone, hope you're all having a wonderful day!",
            "Just signed up for a dance class, can't wait to start!"
        )
    )
);

// Copied from https://stackoverflow.com/a/58259320
function get_rand_datetime()
{
    $randDate = new DateTime();
    $randDate->setTime(mt_rand(0, 23), mt_rand(0, 59));
    return $randDate->format("Y/m/d H:i:s");
}

// Add users and their 2 topics each
foreach($users as $user)
{
    $username = $user['username'];
    $first_name = $user['first_name'];
    $last_name = $user['last_name'];
    $tag = $user['short_signature'];

    $topics = $user['topics'];
    $posts = $user['posts'];

    insert_user($username, $first_name, $last_name, $tag);
    $user_id = get_user_id($username);

    foreach($topics as $topic)
    {
        $date = get_rand_datetime();
        insert_topic($user_id, $date, $topic);
    }
}

// Generate 100 post datetimes (Should have had chatgpt add this to the original array, oops)
$post_dates = [];
for($i = 0; $i < 100; $i++)
{
    array_push($post_dates, get_rand_datetime());
}
rsort($post_dates);

// Add forum posts
foreach($users as $user)
{
    $username = $user['username'];
    $user_id = get_user_id($username);
    foreach($posts as $post)
    {
        $date = array_pop($post_dates);
        $topic = _select('SELECT TopicID FROM Topic ORDER BY RANDOM() LIMIT 1');
        $topic_id = $topic[0]['TopicID'];

        insert_post($user_id, $post, $date, $topic_id);
    }
}

redirect('Homepage.php');
?>
